### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by BigDeepBlue** [Vatson76/Async_API_sprint_2#33]
Далее будет много слов 😄, там ряд рекомендаций и несколько упущенных моментов в проекте.
1. Среди переменных окружения есть одна лишняя: `POSTGRES_URL`. Можно избавиться от нее немного изменив [файл настроек](https://github.com/Vatson76/Async_API_sprint_2/blob/4f9ccdc1b05b5e3b82f38825081b0885e16f14c2/auth_service/src/settings.py#L6):
      ```
      class Database(BaseSettings):
          db: str = ...
          user: str = ...
          password: str = ...
          host:str = Field(..., env='DB_HOST')
          port:int = Field(..., env='DB_PORT')
      
          class Config:
              env_prefix = 'postgres_'
      
      
      class Settings(BaseSettings):
          JWT_SECRET_KEY: str = 'top secret'
      
          db = Database()
          POSTGRES_URL: PostgresDsn = f'postgresql://{db.user}:{db.password}@{db.host}:{db.port}/{db.db}'
      ```
2. Вот [такой способ](https://github.com/Vatson76/Async_API_sprint_2/blob/4f9ccdc1b05b5e3b82f38825081b0885e16f14c2/auth_service/src/app.py#L74) инициализации и обновления таблиц БД не самый лучший, а в реальных проектах - недопустимый. Только именованные миграции. Попробуйте https://alembic.sqlalchemy.org/en/latest/
3. Избегайте любого хардкода в проекте. В том числе и такой мелочи, как [коды ответов](https://github.com/Vatson76/Async_API_sprint_2/blob/4f9ccdc1b05b5e3b82f38825081b0885e16f14c2/auth_service/src/app.py#L46) сервера. Пользуйтесь https://docs.python.org/3/library/http.html, как вы это делаете парой строчек ниже.
4. В моделях `auth_service/src/models` везде где вы используете поле типа String, нужно указывать максимальную длину. Это нужно делать. Это позволяет оптимизировать расход ресурсов и защищает от случаев, когда в такие поля пытаются вставить огромные тексты. Если нужно не ограничивать длину строки, то лучше использовать поле Text
5. Нужно озаботится тем, что если пользователь будет удален, то и все [записи его истории](https://github.com/Vatson76/Async_API_sprint_2/blob/4f9ccdc1b05b5e3b82f38825081b0885e16f14c2/auth_service/src/models/users.py#L63) входов были удалены автоматически. 
https://docs.sqlalchemy.org/en/20/orm/cascades.html#using-foreign-key-on-delete-cascade-with-orm-relationships
Или тут с примерами https://esmithy.net/2020/06/20/sqlalchemy-cascade-delete/
Это же касается и таблицы `UserRole`
6. Обязательно должно быть версионирование адресов "ручек" и папок в проекте. Как делали в сервисе выдачи контента.
7. [Консольные команды](https://github.com/Vatson76/Async_API_sprint_2/blob/4f9ccdc1b05b5e3b82f38825081b0885e16f14c2/auth_service/src/api/roles.py#L14) нужно вынести в отдельное место. Их со временем может быть много.
8. Любое API нужно документировать. Обратите внимание на https://github.com/flasgger/flasgger
9. Выдача истории входов пользователя должна быть с пагинацией, там через 2-3 месяца будут выдаваться сотни записей.
10. [Лишний](https://github.com/Vatson76/Async_API_sprint_2/blob/4f9ccdc1b05b5e3b82f38825081b0885e16f14c2/auth_service/src/services/helpers.py#L25) else.  Это детская ошибка :) https://pheanex.github.io/pylint/ (еще в паре мест есть подобное)
11. Обновите README, там нет ничего про сервис авторизации.
12. И мы пишем тесты для всего API, сервис авторизации тоже нужно покрыть, хотя бы основную логику, и достаточно будет unit тестов.

**Comment by Vatson76** [comment]
1,2 готово

**Comment by Vatson76** [comment]
3, 6, 11 готово

**Comment by BigDeepBlue** [comment]
Миграции используйте только именованные. Alembic это умеет.
